[manifest]
version = "1.0.0"
dump_lua = true
priority = 10

[[patches]]
[patches.pattern]
target = "card.lua"
pattern = "self.children.center.states.hover = self.states.hover"
position = "before"
payload = '''
if self.config.center == G.P_CENTERS["c_mars"] then 
    local scale = G.SETTINGS.GRAPHICS.texture_scaling
    self.children.center = Sprite(self.T.x, self.T.y, self.T.w, self.T.h, {name="Tarot", image = love.graphics.newImage("Mods/mars_bar/"..scale.."x/mars.png", {mipmaps = true, dpiscale = scale}), px=71, py=95}, {x=0, y=0})
end
'''
match_indent = true
overwrite = false
