[manifest]
version = "1.0.0"
dump_lua = true
priority = 10

[[patches]]
[patches.pattern]
target = "card.lua"
pattern = "self.children.center.states.hover = self.states.hover"
position = "before"
payload = '''
if self.config.center == G.P_CENTERS["c_mars"] then 
    local scale = G.SETTINGS.GRAPHICS.texture_scaling
    self.children.center = Sprite(self.T.x, self.T.y, self.T.w, self.T.h, {name="Tarot", image = love.graphics.newImage("Mods/mars_bar/"..scale.."x/mars.png", {mipmaps = true, dpiscale = scale}), px=71, py=95}, {x=0, y=0})
end
'''
match_indent = true
overwrite = false

[[patches]]
[patches.pattern]
target = "functions/UI_definitions.lua"
pattern = '''badges[#badges + 1] = create_badge(((card.ability.name == 'Pluto' or card.ability.name == 'Ceres' or card.ability.name == 'Eris') and localize('k_dwarf_planet')) or (card.ability.name == 'Planet X' and localize('k_planet_q') or card_type),card_type_colour, nil, 1.2)'''
position = "at"
payload = '''badges[#badges + 1] = create_badge(((card.ability.name == 'Pluto' or card.ability.name == 'Ceres' or card.ability.name == 'Eris') and localize('k_dwarf_planet')) or (card.ability.name == 'Mars' and 'Bar') or (card.ability.name == 'Planet X' and localize('k_planet_q') or card_type),card_type_colour, nil, 1.2)'''
match_indent = true
overwrite = false